# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'tela_principal.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class Ui_TelaPrincipal(object):
    def setupUi(self, TelaPrincipal):
        if not TelaPrincipal.objectName():
            TelaPrincipal.setObjectName(u"TelaPrincipal")
        TelaPrincipal.resize(971, 690)
        icon = QIcon()
        icon.addFile(u"_img/icone_principal.png", QSize(), QIcon.Normal, QIcon.Off)
        TelaPrincipal.setWindowIcon(icon)
        self.menu_cadastro_usuario = QAction(TelaPrincipal)
        self.menu_cadastro_usuario.setObjectName(u"menu_cadastro_usuario")
        icon1 = QIcon()
        icon1.addFile(u"_img/usuario.png", QSize(), QIcon.Normal, QIcon.Off)
        self.menu_cadastro_usuario.setIcon(icon1)
        font = QFont()
        font.setPointSize(12)
        self.menu_cadastro_usuario.setFont(font)
        self.menu_consulta_usuarios = QAction(TelaPrincipal)
        self.menu_consulta_usuarios.setObjectName(u"menu_consulta_usuarios")
        icon2 = QIcon()
        icon2.addFile(u"_img/consulta_usuario.png", QSize(), QIcon.Normal, QIcon.Off)
        self.menu_consulta_usuarios.setIcon(icon2)
        self.menu_consulta_usuarios.setFont(font)
        self.menu_sair = QAction(TelaPrincipal)
        self.menu_sair.setObjectName(u"menu_sair")
        icon3 = QIcon()
        icon3.addFile(u"_img/sair.png", QSize(), QIcon.Normal, QIcon.Off)
        self.menu_sair.setIcon(icon3)
        self.menu_cadastro_personagem = QAction(TelaPrincipal)
        self.menu_cadastro_personagem.setObjectName(u"menu_cadastro_personagem")
        icon4 = QIcon()
        icon4.addFile(u"_img/personagem.png", QSize(), QIcon.Normal, QIcon.Off)
        self.menu_cadastro_personagem.setIcon(icon4)
        self.menu_cadastro_personagem.setFont(font)
        self.menu_consultar_personagem = QAction(TelaPrincipal)
        self.menu_consultar_personagem.setObjectName(u"menu_consultar_personagem")
        icon5 = QIcon()
        icon5.addFile(u"_img/consultar_personagem.png", QSize(), QIcon.Normal, QIcon.Off)
        self.menu_consultar_personagem.setIcon(icon5)
        self.menu_consultar_personagem.setFont(font)
        self.menu_cadastro_classes = QAction(TelaPrincipal)
        self.menu_cadastro_classes.setObjectName(u"menu_cadastro_classes")
        icon6 = QIcon()
        icon6.addFile(u"_img/escudo.png", QSize(), QIcon.Normal, QIcon.Off)
        self.menu_cadastro_classes.setIcon(icon6)
        self.menu_cadastro_classes.setFont(font)
        self.menu_cadastro_raca = QAction(TelaPrincipal)
        self.menu_cadastro_raca.setObjectName(u"menu_cadastro_raca")
        icon7 = QIcon()
        icon7.addFile(u"_img/raca.png", QSize(), QIcon.Normal, QIcon.Off)
        self.menu_cadastro_raca.setIcon(icon7)
        self.menu_cadastro_raca.setFont(font)
        self.menu_cadastrar_monstros = QAction(TelaPrincipal)
        self.menu_cadastrar_monstros.setObjectName(u"menu_cadastrar_monstros")
        icon8 = QIcon()
        icon8.addFile(u"_img/monstros.png", QSize(), QIcon.Normal, QIcon.Off)
        self.menu_cadastrar_monstros.setIcon(icon8)
        self.menu_cadastrar_monstros.setFont(font)
        self.menu_consultar_monstros = QAction(TelaPrincipal)
        self.menu_consultar_monstros.setObjectName(u"menu_consultar_monstros")
        icon9 = QIcon()
        icon9.addFile(u"_img/consulta_monstros.png", QSize(), QIcon.Normal, QIcon.Off)
        self.menu_consultar_monstros.setIcon(icon9)
        self.menu_consultar_monstros.setFont(font)
        self.menu_rolar_dados = QAction(TelaPrincipal)
        self.menu_rolar_dados.setObjectName(u"menu_rolar_dados")
        icon10 = QIcon()
        icon10.addFile(u"_img/dado.png", QSize(), QIcon.Normal, QIcon.Off)
        self.menu_rolar_dados.setIcon(icon10)
        self.menu_rolar_dados.setFont(font)
        self.menu_combate = QAction(TelaPrincipal)
        self.menu_combate.setObjectName(u"menu_combate")
        icon11 = QIcon()
        icon11.addFile(u"_img/batalha.png", QSize(), QIcon.Normal, QIcon.Off)
        self.menu_combate.setIcon(icon11)
        self.menu_combate.setFont(font)
        self.menu_nivel_desafio = QAction(TelaPrincipal)
        self.menu_nivel_desafio.setObjectName(u"menu_nivel_desafio")
        icon12 = QIcon()
        icon12.addFile(u"_img/nivel.png", QSize(), QIcon.Normal, QIcon.Off)
        self.menu_nivel_desafio.setIcon(icon12)
        self.menu_nivel_desafio.setFont(font)
        self.menu_sobre = QAction(TelaPrincipal)
        self.menu_sobre.setObjectName(u"menu_sobre")
        icon13 = QIcon()
        icon13.addFile(u"_img/sobre.png", QSize(), QIcon.Normal, QIcon.Off)
        self.menu_sobre.setIcon(icon13)
        self.menu_sobre.setFont(font)
        self.centralwidget = QWidget(TelaPrincipal)
        self.centralwidget.setObjectName(u"centralwidget")
        self.verticalLayout = QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.frame = QFrame(self.centralwidget)
        self.frame.setObjectName(u"frame")
        self.frame.setFrameShape(QFrame.StyledPanel)
        self.frame.setFrameShadow(QFrame.Raised)
        self.horizontalLayout = QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.label = QLabel(self.frame)
        self.label.setObjectName(u"label")
        self.label.setPixmap(QPixmap(u"_img/principal.png"))
        self.label.setScaledContents(True)

        self.horizontalLayout.addWidget(self.label)


        self.verticalLayout.addWidget(self.frame)

        self.frame_2 = QFrame(self.centralwidget)
        self.frame_2.setObjectName(u"frame_2")
        sizePolicy = QSizePolicy(QSizePolicy.Minimum, QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setStyleSheet(u"background-color: rgb(138, 0, 0);")
        self.frame_2.setFrameShape(QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QFrame.Raised)
        self.horizontalLayout_2 = QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.label_2 = QLabel(self.frame_2)
        self.label_2.setObjectName(u"label_2")
        sizePolicy1 = QSizePolicy(QSizePolicy.Maximum, QSizePolicy.Preferred)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy1)

        self.horizontalLayout_2.addWidget(self.label_2)

        self.label_nome = QLabel(self.frame_2)
        self.label_nome.setObjectName(u"label_nome")
        sizePolicy2 = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Preferred)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.label_nome.sizePolicy().hasHeightForWidth())
        self.label_nome.setSizePolicy(sizePolicy2)
        font1 = QFont()
        font1.setPointSize(12)
        font1.setBold(True)
        font1.setWeight(75)
        self.label_nome.setFont(font1)
        self.label_nome.setStyleSheet(u"color: rgb(255, 255, 255);")

        self.horizontalLayout_2.addWidget(self.label_nome)


        self.verticalLayout.addWidget(self.frame_2)

        TelaPrincipal.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(TelaPrincipal)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 971, 21))
        self.menuUsu_rios = QMenu(self.menubar)
        self.menuUsu_rios.setObjectName(u"menuUsu_rios")
        self.menuPersonagens = QMenu(self.menubar)
        self.menuPersonagens.setObjectName(u"menuPersonagens")
        self.menuMonstros = QMenu(self.menubar)
        self.menuMonstros.setObjectName(u"menuMonstros")
        self.menuDados = QMenu(self.menubar)
        self.menuDados.setObjectName(u"menuDados")
        self.menuCombate = QMenu(self.menubar)
        self.menuCombate.setObjectName(u"menuCombate")
        self.menuSobre = QMenu(self.menubar)
        self.menuSobre.setObjectName(u"menuSobre")
        TelaPrincipal.setMenuBar(self.menubar)

        self.menubar.addAction(self.menuUsu_rios.menuAction())
        self.menubar.addAction(self.menuPersonagens.menuAction())
        self.menubar.addAction(self.menuMonstros.menuAction())
        self.menubar.addAction(self.menuDados.menuAction())
        self.menubar.addAction(self.menuCombate.menuAction())
        self.menubar.addAction(self.menuSobre.menuAction())
        self.menuUsu_rios.addAction(self.menu_cadastro_usuario)
        self.menuUsu_rios.addAction(self.menu_consulta_usuarios)
        self.menuUsu_rios.addSeparator()
        self.menuUsu_rios.addAction(self.menu_sair)
        self.menuPersonagens.addAction(self.menu_cadastro_personagem)
        self.menuPersonagens.addAction(self.menu_consultar_personagem)
        self.menuPersonagens.addAction(self.menu_cadastro_classes)
        self.menuPersonagens.addAction(self.menu_cadastro_raca)
        self.menuMonstros.addAction(self.menu_cadastrar_monstros)
        self.menuMonstros.addAction(self.menu_consultar_monstros)
        self.menuDados.addAction(self.menu_rolar_dados)
        self.menuCombate.addAction(self.menu_combate)
        self.menuCombate.addAction(self.menu_nivel_desafio)
        self.menuSobre.addAction(self.menu_sobre)

        self.retranslateUi(TelaPrincipal)

        QMetaObject.connectSlotsByName(TelaPrincipal)
    # setupUi

    def retranslateUi(self, TelaPrincipal):
        TelaPrincipal.setWindowTitle(QCoreApplication.translate("TelaPrincipal", u"MainWindow", None))
        self.menu_cadastro_usuario.setText(QCoreApplication.translate("TelaPrincipal", u"Cadastro de Usu\u00e1rios", None))
        self.menu_consulta_usuarios.setText(QCoreApplication.translate("TelaPrincipal", u"Consulta de Usu\u00e1rios", None))
        self.menu_sair.setText(QCoreApplication.translate("TelaPrincipal", u"Sair", None))
        self.menu_cadastro_personagem.setText(QCoreApplication.translate("TelaPrincipal", u"Cadastro de Personagens", None))
        self.menu_consultar_personagem.setText(QCoreApplication.translate("TelaPrincipal", u"Consultar Personagens", None))
        self.menu_cadastro_classes.setText(QCoreApplication.translate("TelaPrincipal", u"Cadastro de Classes", None))
        self.menu_cadastro_raca.setText(QCoreApplication.translate("TelaPrincipal", u"Cadastro de Ra\u00e7a", None))
        self.menu_cadastrar_monstros.setText(QCoreApplication.translate("TelaPrincipal", u"Cadastrar Monstros", None))
        self.menu_consultar_monstros.setText(QCoreApplication.translate("TelaPrincipal", u"Consultar Monstros", None))
        self.menu_rolar_dados.setText(QCoreApplication.translate("TelaPrincipal", u"Rolar Dados", None))
        self.menu_combate.setText(QCoreApplication.translate("TelaPrincipal", u"Combate", None))
        self.menu_nivel_desafio.setText(QCoreApplication.translate("TelaPrincipal", u"N\u00edvel de desafios", None))
        self.menu_sobre.setText(QCoreApplication.translate("TelaPrincipal", u"Sobre", None))
        self.label.setText("")
        self.label_2.setText(QCoreApplication.translate("TelaPrincipal", u"<html><head/><body><p><span style=\" font-size:12pt; font-weight:600; color:#ffffff;\">Mestre:</span></p></body></html>", None))
        self.label_nome.setText("")
        self.menuUsu_rios.setTitle(QCoreApplication.translate("TelaPrincipal", u"Usu\u00e1rios", None))
        self.menuPersonagens.setTitle(QCoreApplication.translate("TelaPrincipal", u"Personagens", None))
        self.menuMonstros.setTitle(QCoreApplication.translate("TelaPrincipal", u"Monstros", None))
        self.menuDados.setTitle(QCoreApplication.translate("TelaPrincipal", u"Dados", None))
        self.menuCombate.setTitle(QCoreApplication.translate("TelaPrincipal", u"Combate", None))
        self.menuSobre.setTitle(QCoreApplication.translate("TelaPrincipal", u"Ajuda", None))
    # retranslateUi

